name: teampulse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ðŸ”¹ Ãšltimas versiones estables (2025)
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.4
  table_calendar: ^3.0.9
  intl: ^0.20.2
  fl_chart: ^0.69.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  easy_localization: ^3.0.7
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/translations/
